"""
Talent OS — WS-E.8/WS-E.10 retention admin endpoints (JWT-protected,
role='admin').

Owner decision (retention-kolommen branch, fifth round): after four
rounds of guard fixes it became clear that every "no reaction" signal
core/retention.py's selectors can check lives in a channel this backend
does not reliably record — the actual work (a phone call, a LinkedIn
thread, a reply landing in a recruiter's own mailbox) happens outside
this system. The owner therefore ended automatic purging entirely, at
any confidence level. What is left:

  1. GET  /api/v1/admin/retention/table — unchanged: the bewaartabel as
     structured rows plus the exact Markdown the register/SOP carry.
  2. POST /api/v1/admin/retention/run — counts only, always. The
     dry_run=false branch that used to actually purge is gone outright
     (not merely defaulted off) — see run_retention() below and
     tests/test_ws_e10_no_unapproved_purge_path.py, which fails if a
     later change reopens it.
  3. GET  /api/v1/admin/retention/review — the monthly review queue
     (services/scheduler.py generate_retention_review(),
     retention_review_items via migrations/036_retention_review_queue.py):
     per person/row, the category, the date the term expired
     (term_expired_at), and which protective signal was absent
     (signal_missing_nl) — exactly what the owner asked the monthly list
     to show.
  4. GET  /api/v1/admin/retention/review/summary — counts per category/
     status only, no subject rows — safe to feed to a Telegram-facing
     routine (VERWERKINGSREGISTER.md §6 punt 6(d): that channel carries
     no personal data by design; a count of how many people are waiting
     for review is not the list itself).
  5. POST /api/v1/admin/retention/review/generate — runs the same
     generation logic on demand (in addition to the monthly cron) —
     read/queue-only, deletes nothing.
  6. POST /api/v1/admin/retention/review/{item_id}/approve — THE ONLY
     PATH IN THIS BACKEND THAT ACTUALLY ANONYMISES/DELETES A RETENTION-
     TABLE SUBJECT. Requires confirm="APPROVE", re-verifies the subject
     is still eligible right before acting (a protective signal can have
     appeared since the item was queued), then anonymises (erase_person())
     or hard-deletes per the item's own `action`, writes one
     retention_review_decisions row (who/when, audit-trail pattern of
     routers/admin.py's consent endpoints) and one audit_log row
     (json.dumps'd, counts/keys only, never PII — commit 72b4bcd).
  7. POST /api/v1/admin/retention/review/{item_id}/reject — no confirm
     needed (nothing irreversible happens): marks the item 'rejected'.
     If the same subject is queued again on a later monthly run, the
     existing row is reopened rather than silently re-inserted --
     `reappeared_after_rejection_at` makes a previously-skipped person
     visible again, not just present.
  8. POST /api/v1/admin/retention/review/bulk — approve/reject several
     items (by id list or by category) in one call; each item still goes
     through the exact same per-item re-verify+act path as #6/#7 above,
     just looped — never a single bulk DELETE.

Apollo bulk-pool cleanup (VERWERKINGSREGISTER.md §2.6, §5.7) used to be
its own direct-delete endpoint here
(POST /api/v1/admin/apollo-pool/purge, dry_run=false + confirm). It
shares the exact same guard family (core.retention.
CANDIDATE_NO_REACTION_GUARD_SQL) that motivated this whole redesign, so
WS-E.10 folds its real deletion into the SAME review queue instead
(category='apollo_pool_purge', generated by
services/scheduler.py generate_retention_review()) — the endpoint below
keeps its dry-run preview (harmless, read-only) but the dry_run=false
branch is gone outright, same as run_retention()'s.
"""
import json
import logging
from typing import List, Optional

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel

from core.database import fetch_all, fetch_one, execute
from core.deps import require_role
from core import retention
from services import scheduler as scheduler_service

logger = logging.getLogger("talent_os.retention_admin")

router = APIRouter(prefix="/api/v1/admin/retention", tags=["retention-admin"])
apollo_pool_router = APIRouter(prefix="/api/v1/admin/apollo-pool", tags=["retention-admin"])

# Whitelist of tables an approve/reject-driven DELETE is ever allowed to
# name -- every one of these is a value this router's own generation code
# wrote into retention_review_items.subject_table, never user input, but
# kept as a closed set anyway so a hard_delete branch can never be pointed
# at an arbitrary table string.
_HARD_DELETE_TABLES = frozenset({"quiz_submissions", "contact_submissions", "candidates", "client_prospects"})


class RetentionRunRequest(BaseModel):
    dry_run: bool = True
    confirm: Optional[str] = None


@router.get("/table")
async def get_retention_table(current_user: dict = Depends(require_role("admin"))):
    """The bewaartabel as both structured rows and the exact Markdown the
    register/SOP carry (docs/VERWERKINGSREGISTER.md §1.4, docs/SOURCING-SOP.md
    §6) — for admins verifying the two stay in sync, not just tests."""
    return {
        "markdown": retention.render_markdown(),
        "rows": [
            {
                "key": r.key,
                "categorie": r.categorie,
                "bewaartermijn": r.bewaartermijn,
                "bron_opmerking": r.bron_opmerking,
                "legal_basis_ref": r.legal_basis_ref,
                "anchor_column": r.anchor_column,
                "action": r.action,
                "schema_ready": r.schema_ready,
                "signal_missing_nl": r.signal_missing_nl,
            }
            for r in retention.RETENTION_TABLE
        ],
    }


@router.post("/run")
async def run_retention(
    payload: RetentionRunRequest,
    current_user: dict = Depends(require_role("admin")),
):
    """Counts per category, always — never writes anything. The
    dry_run=false + confirm="PURGE" branch that used to actually
    anonymise/delete here is gone outright (WS-E.10, owner decision): a
    real purge now only ever happens from an approved
    retention_review_items row (POST .../review/{item_id}/approve), never
    from this endpoint at any body value. See
    tests/test_ws_e10_no_unapproved_purge_path.py, which fails if a later
    change reopens a `dry_run=false` branch here."""
    if not payload.dry_run:
        raise HTTPException(
            status_code=410,
            detail={
                "code": "retention_run_no_longer_purges",
                "message": (
                    "Dit endpoint wist niets meer, ongeacht de waarde van dry_run of confirm. "
                    "Een echte verwijdering loopt sinds WS-E.10 uitsluitend via "
                    "POST /api/v1/admin/retention/review/{item_id}/approve, na goedkeuring van de "
                    "maandelijkse beoordelingslijst (GET /api/v1/admin/retention/review)."
                ),
            },
        )
    categories = []
    for row in retention.RETENTION_TABLE:
        if row.action in ("retain", "infra_only"):
            categories.append({"key": row.key, "status": "not_applicable", "count": None})
        elif not row.schema_ready:
            categories.append({"key": row.key, "status": "schema_not_ready", "count": None})
        else:
            try:
                count = len(await scheduler_service._live_rows_for_category(row))
                categories.append({"key": row.key, "status": "counted", "count": count})
            except Exception:
                logger.exception("run_retention: category %s failed", row.key)
                categories.append({"key": row.key, "status": "error", "count": None})
    return {"dry_run": True, "categories": categories}


# ── Monthly review queue (WS-E.10) ───────────────────────────────────────

class ReviewDecisionRequest(BaseModel):
    confirm: Optional[str] = None
    note: Optional[str] = None


class ReviewBulkRequest(BaseModel):
    decision: str  # "approved" | "rejected"
    ids: Optional[List[int]] = None
    category: Optional[str] = None
    confirm: Optional[str] = None
    note: Optional[str] = None


REVIEW_APPROVE_CONFIRM = "APPROVE"


@router.get("/review")
async def list_review_items(
    status: str = "pending",
    category: Optional[str] = None,
    current_user: dict = Depends(require_role("admin")),
):
    """The monthly list itself — one row per person/subject currently (or
    previously, with status != 'pending') queued, carrying exactly what
    the owner asked for: category, term_expired_at (the date the term
    expired), and signal_missing_nl (which protective signal was absent).
    `status="all"` lists every status; the default `status="pending"`
    matches what an admin screen's default view should show."""
    where = []
    params: list = []
    if status != "all":
        params.append(status)
        where.append(f"status = ${len(params)}")
    if category:
        params.append(category)
        where.append(f"category = ${len(params)}")
    where_sql = f"WHERE {' AND '.join(where)}" if where else ""
    rows = await fetch_all(
        f"""SELECT id, category, subject_table, subject_id, email, action, term_expired_at,
                   signal_missing_nl, status, first_seen_at, last_seen_at,
                   reappeared_after_rejection_at, purged_at
            FROM retention_review_items {where_sql}
            ORDER BY term_expired_at ASC NULLS LAST, id ASC""",
        *params,
    )
    return {"items": rows}


@router.get("/review/summary")
async def review_summary(current_user: dict = Depends(require_role("admin"))):
    """Counts only, per category and status — no subject rows, no e-mail
    addresses, no names. This is the shape a Telegram-facing routine may
    read (VERWERKINGSREGISTER.md §6 punt 6(d): that channel carries no
    personal data by design) to signal "the monthly list is ready" —
    a signal that a list exists is not the list itself."""
    rows = await fetch_all(
        "SELECT category, status, COUNT(*) AS n FROM retention_review_items GROUP BY category, status"
    )
    pending_total = sum(r["n"] for r in rows if r["status"] == "pending")
    return {"pending_total": pending_total, "by_category": rows}


@router.post("/review/generate")
async def generate_review(current_user: dict = Depends(require_role("admin"))):
    """Runs the same queue-generation logic the monthly cron uses
    (services/scheduler.py generate_retention_review()), on demand.
    Read/queue-only — see that function's own docstring: it never touches
    the GDPR erasure routine or deletes a candidate/prospect/user row."""
    return await scheduler_service.generate_retention_review()


async def _is_still_eligible(item: dict) -> bool:
    """Re-verify right before acting that the subject is still actually
    due -- a protective signal (a match, a reply logged in `activities`,
    an active client relationship, ...) can have appeared between the
    monthly generation run and the moment an admin clicks approve.
    Prevents a stale queue row from ever being the sole basis for a real
    deletion."""
    category = item["category"]
    subject_id = item["subject_id"]
    if category == "leads_quiz":
        table = item["subject_table"]
        if table not in ("quiz_submissions", "contact_submissions"):
            return False
        row = await fetch_one(
            f"SELECT id FROM {table} WHERE id = $1 AND created_at <= (NOW() - INTERVAL '12 months')",
            subject_id,
        )
        return row is not None
    if category == "apollo_pool_purge":
        rows = await fetch_all(retention.APOLLO_POOL_TARGET_SQL)
        return any(r["id"] == subject_id for r in rows)
    row_def = retention.get_row(category)
    if row_def is None:
        return False
    live_rows = await scheduler_service._live_rows_for_category(row_def)
    return any(r["id"] == subject_id for r in live_rows)


async def _approve_one(item_id: int, actor_id: int, note: Optional[str]) -> dict:
    """The one and only place in this backend that anonymises/deletes a
    retention-table subject. Re-verifies eligibility, acts per the item's
    own `action`, then records the decision (retention_review_decisions,
    audit-trail pattern of routers/admin.py's consent endpoints) and the
    audit_log row (counts/keys only, never PII)."""
    item = await fetch_one("SELECT * FROM retention_review_items WHERE id = $1", item_id)
    if not item:
        raise HTTPException(status_code=404, detail="Review item not found")
    if item["status"] not in ("pending", "rejected", "no_longer_eligible"):
        raise HTTPException(
            status_code=409,
            detail={
                "code": "retention_review_item_not_actionable",
                "message": f"Item {item_id} has status '{item['status']}', cannot approve.",
            },
        )

    if not await _is_still_eligible(item):
        await execute(
            "UPDATE retention_review_items SET status = 'no_longer_eligible', last_seen_at = NOW() WHERE id = $1",
            item_id,
        )
        raise HTTPException(
            status_code=409,
            detail={
                "code": "retention_review_item_no_longer_eligible",
                "message": (
                    f"Item {item_id} is niet meer in aanmerking gekomen (een beschermend signaal is "
                    "sindsdien verschenen) -- niet gewist."
                ),
            },
        )

    from routers.gdpr import erase_person

    if item["action"] == "anonymise":
        if not item["email"]:
            raise HTTPException(status_code=500, detail="anonymise action requires an e-mail address")
        await erase_person(item["email"], actor_id=actor_id, reason=f"retention_purge:{item['category']}")
    elif item["action"] == "hard_delete":
        table = item["subject_table"]
        if table not in _HARD_DELETE_TABLES:
            raise HTTPException(status_code=500, detail=f"unexpected subject_table {table!r}")
        await execute(f"DELETE FROM {table} WHERE id = $1", item["subject_id"])
    else:
        raise HTTPException(status_code=500, detail=f"unexpected action {item['action']!r}")

    await execute(
        "UPDATE retention_review_items SET status = 'purged', purged_at = NOW(), last_seen_at = NOW() WHERE id = $1",
        item_id,
    )
    await execute(
        "INSERT INTO retention_review_decisions (review_item_id, decision, actor_id, note) VALUES ($1, $2, $3, $4)",
        item_id, "approved", actor_id, note,
    )
    await execute(
        "INSERT INTO audit_log (action, actor_id, target_type, target_id, changes) VALUES ($1, $2, $3, $4, $5::jsonb)",
        "retention_review_approve", actor_id, "retention_review_item", item_id,
        json.dumps({"category": item["category"], "action": item["action"]}),
    )
    logger.warning(
        "Retention review item approved by admin user_id=%s: item_id=%s category=%s action=%s",
        actor_id, item_id, item["category"], item["action"],
    )
    return {"id": item_id, "status": "purged"}


async def _reject_one(item_id: int, actor_id: int, note: Optional[str]) -> dict:
    item = await fetch_one("SELECT * FROM retention_review_items WHERE id = $1", item_id)
    if not item:
        raise HTTPException(status_code=404, detail="Review item not found")
    if item["status"] == "purged":
        raise HTTPException(
            status_code=409,
            detail={"code": "retention_review_item_already_purged", "message": f"Item {item_id} was already purged."},
        )
    await execute(
        "UPDATE retention_review_items SET status = 'rejected', last_seen_at = NOW() WHERE id = $1", item_id,
    )
    await execute(
        "INSERT INTO retention_review_decisions (review_item_id, decision, actor_id, note) VALUES ($1, $2, $3, $4)",
        item_id, "rejected", actor_id, note,
    )
    return {"id": item_id, "status": "rejected"}


@router.post("/review/{item_id}/approve")
async def approve_review_item(
    item_id: int,
    payload: ReviewDecisionRequest,
    current_user: dict = Depends(require_role("admin")),
):
    """Confirm="APPROVE" required -- this is the only endpoint in this
    backend that actually anonymises/deletes a retention-table subject."""
    if payload.confirm != REVIEW_APPROVE_CONFIRM:
        raise HTTPException(
            status_code=409,
            detail={
                "code": "retention_review_approve_requires_confirm",
                "message": f'confirm: "{REVIEW_APPROVE_CONFIRM}" is required.',
            },
        )
    return await _approve_one(item_id, current_user["id"], payload.note)


@router.post("/review/{item_id}/reject")
async def reject_review_item(
    item_id: int,
    payload: ReviewDecisionRequest,
    current_user: dict = Depends(require_role("admin")),
):
    """No confirm required -- rejecting is the safe default (nothing
    irreversible happens); it only marks the item so it does not get
    silently re-approved, and stays visible if it reappears later."""
    return await _reject_one(item_id, current_user["id"], payload.note)


@router.post("/review/bulk")
async def bulk_review_decision(
    payload: ReviewBulkRequest,
    current_user: dict = Depends(require_role("admin")),
):
    """Approve or reject several items in one call -- by explicit `ids`,
    or every currently-pending item in `category`. Still one _approve_one
    / _reject_one call per item (never a single bulk DELETE), so a
    partial failure part-way through leaves an accurate, per-item audit
    trail instead of an all-or-nothing black box."""
    if payload.decision not in ("approved", "rejected"):
        raise HTTPException(status_code=422, detail="decision must be 'approved' or 'rejected'")
    if payload.decision == "approved" and payload.confirm != REVIEW_APPROVE_CONFIRM:
        raise HTTPException(
            status_code=409,
            detail={
                "code": "retention_review_approve_requires_confirm",
                "message": f'confirm: "{REVIEW_APPROVE_CONFIRM}" is required.',
            },
        )

    if payload.ids:
        ids = payload.ids
    elif payload.category:
        rows = await fetch_all(
            "SELECT id FROM retention_review_items WHERE category = $1 AND status = 'pending'", payload.category,
        )
        ids = [r["id"] for r in rows]
    else:
        raise HTTPException(status_code=422, detail="either ids or category is required")

    results = []
    for item_id in ids:
        try:
            if payload.decision == "approved":
                results.append(await _approve_one(item_id, current_user["id"], payload.note))
            else:
                results.append(await _reject_one(item_id, current_user["id"], payload.note))
        except HTTPException as exc:
            results.append({"id": item_id, "status": "error", "detail": exc.detail})
    return {"results": results}


# ── Apollo bulk-pool cleanup (VERWERKINGSREGISTER.md §2.6, §5.7) ─────────
#
# security-auditor follow-up (WS-E.8 HIGH): pool_origin='apollo' plus a
# missing source_url is not by itself proof the row is inert bulk-harvest
# noise -- an Apollo-sourced candidate can still have picked up a real
# match, a client pipeline entry, a recorded activity, a portal account,
# a placement, or be the (anonymised) subject of a presented-candidate
# outreach draft to a client_prospect, all independent of source_url ever
# being backfilled.
#
# WS-E.10 (owner decision, fifth round): the guarded selectors below moved
# to core/retention.py (APOLLO_POOL_ROWS_SQL / APOLLO_POOL_TARGET_SQL) so
# services/scheduler.py's generate_retention_review() can queue this same
# pool into retention_review_items under category='apollo_pool_purge' --
# the names here are kept as aliases (same object, not a copy) so this
# module's own dry-run preview and its existing tests are unaffected.
_POOL_ROWS_SQL = retention.APOLLO_POOL_ROWS_SQL
_TARGET_ROWS_SQL = retention.APOLLO_POOL_TARGET_SQL


class ApolloPoolPurgeRequest(BaseModel):
    dry_run: bool = True
    confirm: Optional[str] = None


APOLLO_POOL_CONFIRM = "DELETE APOLLO POOL"


@apollo_pool_router.post("/purge")
async def purge_apollo_pool(
    payload: ApolloPoolPurgeRequest,
    current_user: dict = Depends(require_role("admin")),
):
    """dry_run=true (default, unchanged): a read-only preview, same shape
    as before WS-E.10.

    dry_run=false is gone outright (WS-E.10, owner decision, same as
    run_retention()'s): this pool shares the exact CANDIDATE_NO_REACTION_
    GUARD_SQL guard family that motivated ending automatic purging
    everywhere else, so a real deletion here now only ever happens from
    an approved retention_review_items row
    (category='apollo_pool_purge', POST .../review/{item_id}/approve),
    the same as every other category. See
    tests/test_ws_e10_no_unapproved_purge_path.py.
    """
    pool_rows = await fetch_all(_POOL_ROWS_SQL)
    rows = await fetch_all(_TARGET_ROWS_SQL)
    skipped = len(pool_rows) - len(rows)
    with_email = [r for r in rows if r["email"]]
    without_email = [r for r in rows if not r["email"]]

    if payload.dry_run:
        return {
            "dry_run": True,
            "total": len(rows),
            "would_anonymise": len(with_email),
            "would_hard_delete": len(without_email),
            "skipped": skipped,
        }

    raise HTTPException(
        status_code=410,
        detail={
            "code": "apollo_pool_purge_no_longer_deletes",
            "message": (
                "Dit endpoint wist niets meer, ongeacht confirm. Een echte verwijdering loopt sinds "
                "WS-E.10 via de maandelijkse beoordelingslijst (GET /api/v1/admin/retention/review, "
                "category=apollo_pool_purge) en POST /api/v1/admin/retention/review/{item_id}/approve."
            ),
        },
    )
